// <auto-generated />
namespace MiniWS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class initail_dbArnin005 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initail_dbArnin005));
        
        string IMigrationMetadata.Id
        {
            get { return "202005220837364_initail_dbArnin005"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
